services:
  postgres:
    build: ./docker
    image: design-sys-hub-db
    container_name: design-sys-hub-postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - design-sys-hub-data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    restart: always

volumes:
  design-sys-hub-data:
    driver: local
